version: 2
jobs:
  build:
    docker:
      - image: roadiz/php74-runner:latest

    steps:
      - checkout
      - run: apt update
      - run: docker-php-ext-install json
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
  test:
    docker:
      - image: roadiz/php74-runner:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: ./vendor/bin/pest